"""drop is_default from model_configs

Revision ID: 36e5776eb341
Revises: feded377c21d
Create Date: 2026-04-01 12:30:48.337465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36e5776eb341'
down_revision: Union[str, Sequence[str], None] = 'feded377c21d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.drop_column('is_default')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_default', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
