"""add_supports_vision_to_model_configs

Revision ID: b644feb16736
Revises: bb82796a7960
Create Date: 2026-04-04 23:10:24.018037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b644feb16736'
down_revision: Union[str, Sequence[str], None] = 'bb82796a7960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supports_vision', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('model_configs', schema=None) as batch_op:
        batch_op.drop_column('supports_vision')

    # ### end Alembic commands ###
