"""add_store_matching_and_enhanced_line_items

Revision ID: bb82796a7960
Revises: 36e5776eb341
Create Date: 2026-04-01 19:10:17.057457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb82796a7960'
down_revision: Union[str, Sequence[str], None] = '36e5776eb341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_aliases',
    sa.Column('store_id', sa.String(length=36), nullable=False),
    sa.Column('alias_name', sa.String(length=255), nullable=False),
    sa.Column('alias_name_lower', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_name_lower', name='uq_store_alias_name')
    )
    with op.batch_alter_table('store_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_aliases_alias_name_lower'), ['alias_name_lower'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_aliases_store_id'), ['store_id'], unique=False)

    op.create_table('store_merge_suggestions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('store_a_id', sa.String(length=36), nullable=False),
    sa.Column('store_b_id', sa.String(length=36), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['store_a_id'], ['stores.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['store_b_id'], ['stores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('store_a_id', 'store_b_id', name='uq_store_merge_pair')
    )
    with op.batch_alter_table('store_merge_suggestions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_store_merge_suggestions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_store_merge_suggestions_store_a_id'), ['store_a_id'], unique=False)

    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('raw_name', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('discount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_refund', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('tax_code', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('weight_qty', sa.String(length=50), nullable=True))

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('is_refund', sa.Boolean(), nullable=False, server_default=sa.text('0')))

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('merged_into_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key('fk_stores_merged_into_id', 'stores', ['merged_into_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint('fk_stores_merged_into_id', type_='foreignkey')
        batch_op.drop_column('merged_into_id')

    with op.batch_alter_table('receipts', schema=None) as batch_op:
        batch_op.drop_column('is_refund')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('discount')

    with op.batch_alter_table('line_items', schema=None) as batch_op:
        batch_op.drop_column('weight_qty')
        batch_op.drop_column('tax_code')
        batch_op.drop_column('is_refund')
        batch_op.drop_column('discount')
        batch_op.drop_column('raw_name')

    with op.batch_alter_table('store_merge_suggestions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_merge_suggestions_store_a_id'))
        batch_op.drop_index(batch_op.f('ix_store_merge_suggestions_status'))

    op.drop_table('store_merge_suggestions')
    with op.batch_alter_table('store_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_store_aliases_store_id'))
        batch_op.drop_index(batch_op.f('ix_store_aliases_alias_name_lower'))

    op.drop_table('store_aliases')
    # ### end Alembic commands ###
